name: Main Java build pipeline

on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build the ShoppingList project
        run: mvn compile
      - name: Run unit tests for the ShoppingList project
        run: mvn test
      - name: Generate JaCoCo coverage report
        if: always()
        run: mvn jacoco:report
      - name: Publish JaCoCo coverage report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: shopping-list-coverage
          path: ./target/site/jacoco