name: Main Java build pipeline for Thursday

on: push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Compile the project
        run: mvn compile
      - name: Run unit tests on the project
        run: mvn test
      - name: Generate jacoco report
        run: mvn jacoco:report
      - name: Publish jacoco report
        uses: actions/upload-artifact@v2
        with:
          name: shopping-list-coverage
          path:./target/site/jacoco